import {Recipe} from "@/lib/recipe.ts";


export const recipes: Recipe[] = [
    {
        id: "1",
        title: "Creamy Garlic Parmesan Pasta",
        description: "A rich and creamy pasta dish with garlic and parmesan cheese that's ready in under 30 minutes.",
        image: "https://placehold.co/600x400/png",
        prepTime: "10 min",
        cookTime: "15 min",
        totalTime: "25 min",
        servings: 4,
        ingredients: [
            "8 oz fettuccine pasta",
            "2 tbsp butter",
            "4 cloves garlic, minced",
            "1 cup heavy cream",
            "1 cup grated parmesan cheese",
            "Salt and pepper to taste",
            "Fresh parsley, chopped (for garnish)",
        ],
        steps: [
            "Cook pasta according to package instructions. Reserve 1/2 cup of pasta water before draining.",
            "In a large skillet, melt butter over medium heat. Add minced garlic and sauté for 1-2 minutes until fragrant.",
            "Pour in heavy cream and bring to a simmer. Cook for 2-3 minutes until slightly thickened.",
            "Reduce heat to low and gradually whisk in parmesan cheese until melted and smooth.",
            "Add the cooked pasta to the sauce and toss to coat. If the sauce is too thick, add some reserved pasta water.",
            "Season with salt and pepper to taste. Garnish with fresh parsley before serving.",
        ],
    },
    {
        id: "2",
        title: "Honey Soy Glazed Salmon",
        description: "Tender salmon fillets with a sweet and savory glaze, perfect for a quick weeknight dinner.",
        image: "https://placehold.co/600x400/png",
        prepTime: "5 min",
        cookTime: "15 min",
        totalTime: "20 min",
        servings: 2,
        ingredients: [
            "2 salmon fillets (6 oz each)",
            "3 tbsp honey",
            "2 tbsp soy sauce",
            "1 tbsp rice vinegar",
            "2 cloves garlic, minced",
            "1 tsp grated ginger",
            "1 tbsp olive oil",
            "Sesame seeds and sliced green onions for garnish",
        ],
        steps: [
            "In a small bowl, whisk together honey, soy sauce, rice vinegar, garlic, and ginger.",
            "Pat salmon fillets dry with paper towels and season with salt and pepper.",
            "Heat olive oil in a non-stick skillet over medium-high heat.",
            "Place salmon in the skillet, skin-side down, and cook for 4-5 minutes until the skin is crispy.",
            "Flip the salmon and pour the honey soy mixture into the pan. Cook for another 3-4 minutes, basting the salmon with the sauce occasionally.",
            "Remove from heat when salmon is cooked through and the sauce has thickened.",
            "Garnish with sesame seeds and sliced green onions before serving.",
        ],
    },
    {
        id: "3",
        title: "Classic Margherita Pizza",
        description: "A simple yet delicious pizza with fresh tomatoes, mozzarella, and basil on a crispy homemade crust.",
        image: "https://placehold.co/600x400/png",
        prepTime: "30 min",
        cookTime: "15 min",
        totalTime: "45 min",
        servings: 4,
        ingredients: [
            "1 lb pizza dough",
            "1/2 cup pizza sauce",
            "8 oz fresh mozzarella, sliced",
            "2 ripe tomatoes, sliced",
            "Fresh basil leaves",
            "2 tbsp olive oil",
            "Salt and pepper to taste",
            "1/4 cup grated parmesan cheese (optional)",
        ],
        steps: [
            "Preheat oven to 475°F (245°C) with a pizza stone or baking sheet inside.",
            "On a floured surface, roll out the pizza dough to your desired thickness.",
            "Transfer the dough to a piece of parchment paper or a floured pizza peel.",
            "Spread pizza sauce evenly over the dough, leaving a small border for the crust.",
            "Arrange mozzarella slices and tomato slices on top. Drizzle with olive oil and season with salt and pepper.",
            "Carefully transfer the pizza to the preheated stone or baking sheet.",
            "Bake for 12-15 minutes until the crust is golden and the cheese is bubbly.",
            "Remove from oven and immediately top with fresh basil leaves and optional parmesan cheese.",
        ],
    },
    {
        id: "4",
        title: "Vegetable Stir Fry",
        description: "A colorful and nutritious stir fry loaded with fresh vegetables and a flavorful sauce.",
        image: "https://placehold.co/600x400/png",
        prepTime: "15 min",
        cookTime: "10 min",
        totalTime: "25 min",
        servings: 3,
        ingredients: [
            "2 tbsp vegetable oil",
            "2 cloves garlic, minced",
            "1 tbsp grated ginger",
            "1 bell pepper, sliced",
            "1 carrot, julienned",
            "1 cup broccoli florets",
            "1 cup snap peas",
            "1 cup sliced mushrooms",
            "3 tbsp soy sauce",
            "1 tbsp oyster sauce",
            "1 tsp sesame oil",
            "1 tsp cornstarch mixed with 2 tbsp water",
            "Sesame seeds for garnish",
        ],
        steps: [
            "Heat vegetable oil in a large wok or skillet over high heat.",
            "Add garlic and ginger, stir-fry for 30 seconds until fragrant.",
            "Add carrots and broccoli, stir-fry for 2 minutes.",
            "Add bell pepper, snap peas, and mushrooms. Stir-fry for another 3-4 minutes until vegetables are crisp-tender.",
            "In a small bowl, mix soy sauce, oyster sauce, sesame oil, and cornstarch slurry.",
            "Pour sauce over vegetables and stir to coat. Cook for 1-2 minutes until sauce thickens.",
            "Garnish with sesame seeds before serving. Serve over rice or noodles if desired.",
        ],
    },
    {
        id: "5",
        title: "ALCACHOFAS CON HUEVOS ESTRELLADOS",
        description: "Classic homemade chocolate chip cookies with a soft center and crispy edges.",
        image: "https://ep01.epimg.net/elcomidista/imagenes/2017/01/31/receta/1485895793_620703_1485896580_media_normal.jpg",
        prepTime: "15 min",
        cookTime: "12 min",
        totalTime: "27 min",
        servings: 4,
        ingredients: [
            "6 alcachofas",
            "2 huevos de gallinas felices",
            "80 gr de jamón o paletilla (opcional)",
            "Sal",
            "Pimienta"
        ],
        steps: [
            "Cortar las puntas de las alcachofas –unos 3 cm– con un cuchillo afilado. Pelar las alcachofas con las manos, quitando las hojas más duras.",
            "Cortar las alcachofas peladas en tiras de medio centímetro y echar en un bol grande con agua y unas ramas de perejil.",
            "En un cazo con aceite de oliva bien caliente freír las alcachofas hasta conseguir un color tostado. Escurrir bien en papel absorbente.",
            "Colocar las alcachofas en dos platos, añadir el huevo frito y el jamón. Salpimentar al gusto, teniendo en cuenta que el jamón ya aporta su sal.",
        ],
    },
    {
        id: "6",
        title: "Avocado Toast with Poached Egg",
        description: "A nutritious breakfast or brunch option featuring creamy avocado and perfectly poached eggs.",
        image: "https://placehold.co/600x400/png",
        prepTime: "10 min",
        cookTime: "5 min",
        totalTime: "15 min",
        servings: 2,
        ingredients: [
            "2 slices whole grain bread",
            "1 ripe avocado",
            "2 large eggs",
            "1 tbsp white vinegar",
            "Salt and pepper to taste",
            "Red pepper flakes (optional)",
            "1 tbsp fresh lemon juice",
            "Microgreens or fresh herbs for garnish",
        ],
        steps: [
            "Toast the bread slices until golden and crisp.",
            "In a small bowl, mash the avocado with lemon juice, salt, and pepper.",
            "Bring a pot of water to a gentle simmer. Add white vinegar.",
            "Crack each egg into a small cup, then gently slide into the simmering water.",
            "Poach eggs for 3-4 minutes for runny yolks, or longer if desired.",
            "Spread mashed avocado evenly on toast slices.",
            "Using a slotted spoon, remove poached eggs and place on top of avocado toast.",
            "Season with additional salt, pepper, and red pepper flakes if desired.",
            "Garnish with microgreens or fresh herbs before serving.",
        ],
    },
]

